// svelte/01-beginner/lab/solution/src/components/TaskColumn.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { Task } from '../lib/types';
  import TaskItem from './TaskItem.svelte';

  interface Props {
    tasks: Task[];
    /** snippet สำหรับหัวคอลัมน์ — ส่ง title + count จาก parent */
    header: Snippet<[{ count: number }]>;
  }

  let { tasks, header }: Props = $props();
</script>

<section class="column">
  <header>
    {@render header({ count: tasks.length })}
  </header>

  <div class="list">
    {#each tasks as task (task.id)}
      <TaskItem {task} />
    {:else}
      <p class="empty">ยังไม่มีงาน</p>
    {/each}
  </div>
</section>

<style>
  .column {
    background: #e2e8f0;
    border-radius: 14px;
    padding: 0.75rem;
    min-height: 280px;
    display: flex;
    flex-direction: column;
    gap: 0.65rem;
  }

  header {
    padding: 0.25rem 0.35rem 0.15rem;
  }

  .list {
    display: flex;
    flex-direction: column;
    gap: 0.55rem;
    flex: 1;
  }

  .empty {
    margin: 0;
    text-align: center;
    color: #64748b;
    font-size: 0.9rem;
    padding: 1.5rem 0.5rem;
  }
</style>

// vue-nuxt/01-beginner/lab/solution/src/components/TaskColumn.vue
<script setup>
import TaskItem from './TaskItem.vue'

defineProps({
  title: { type: String, required: true },
  tasks: { type: Array, required: true },
})

const emit = defineEmits(['move-next', 'toggle-done'])
</script>

<template>
  <section class="column">
    <h2>{{ title }} <small>({{ tasks.length }})</small></h2>
    <ul>
      <li v-for="task in tasks" :key="task.id">
        <TaskItem
          :task="task"
          @move-next="emit('move-next', task.id)"
          @toggle-done="emit('toggle-done', task.id)"
        />
      </li>
    </ul>
  </section>
</template>

<style scoped>
.column {
  background: color-mix(in srgb, Canvas 88%, CanvasText 4%);
  border: 1px solid color-mix(in srgb, CanvasText 12%, transparent);
  border-radius: 12px;
  padding: 0.85rem;
  min-height: 12rem;
}
h2 {
  margin: 0 0 0.75rem;
  text-transform: uppercase;
  font-size: 0.85rem;
  letter-spacing: 0.04em;
}
ul {
  list-style: none;
  margin: 0;
  padding: 0;
  display: grid;
  gap: 0.5rem;
}
small {
  opacity: 0.6;
  font-weight: 500;
}
</style>
