// svelte/01-beginner/lab/solution/src/App.svelte
<script lang="ts">
  import TaskColumn from './components/TaskColumn.svelte';
  import TaskForm from './components/TaskForm.svelte';
  import { board, tasksByStatus } from './lib/board.svelte';
  import { STATUS_LABEL } from './lib/types';

  const total = $derived(board.tasks.length);
  const todoTasks = $derived(tasksByStatus('todo'));
  const doingTasks = $derived(tasksByStatus('doing'));
  const doneTasks = $derived(tasksByStatus('done'));

  $effect(() => {
    console.log(`[board] total tasks = ${total}`);
  });
</script>

<main>
  <header class="hero">
    <div>
      <p class="eyebrow">Svelte 5 · Beginner Lab</p>
      <h1>Task Board</h1>
      <p class="sub">Kanban ง่าย ๆ ด้วย $state / $derived และ snippets</p>
    </div>
    <p class="count">{total} tasks</p>
  </header>

  <TaskForm />

  <div class="board">
    <TaskColumn tasks={todoTasks}>
      {#snippet header({ count })}
        <div class="col-head">
          <h2>{STATUS_LABEL.todo}</h2>
          <span>{count}</span>
        </div>
      {/snippet}
    </TaskColumn>

    <TaskColumn tasks={doingTasks}>
      {#snippet header({ count })}
        <div class="col-head">
          <h2>{STATUS_LABEL.doing}</h2>
          <span>{count}</span>
        </div>
      {/snippet}
    </TaskColumn>

    <TaskColumn tasks={doneTasks}>
      {#snippet header({ count })}
        <div class="col-head">
          <h2>{STATUS_LABEL.done}</h2>
          <span>{count}</span>
        </div>
      {/snippet}
    </TaskColumn>
  </div>
</main>

<style>
  .hero {
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
    gap: 1rem;
    margin-bottom: 1.25rem;
    flex-wrap: wrap;
  }

  .eyebrow {
    margin: 0 0 0.25rem;
    color: #0f766e;
    font-size: 0.85rem;
    font-weight: 600;
    letter-spacing: 0.04em;
    text-transform: uppercase;
  }

  h1 {
    margin: 0;
    font-size: clamp(1.6rem, 3vw, 2rem);
    color: #0f172a;
  }

  .sub {
    margin: 0.35rem 0 0;
    color: #64748b;
  }

  .count {
    margin: 0;
    background: #ccfbf1;
    color: #115e59;
    font-weight: 600;
    border-radius: 999px;
    padding: 0.35rem 0.85rem;
  }

  .board {
    display: grid;
    gap: 0.85rem;
    margin-top: 1.25rem;
  }

  @media (min-width: 860px) {
    .board {
      grid-template-columns: repeat(3, 1fr);
    }
  }

  .col-head {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 0.5rem;
  }

  .col-head h2 {
    margin: 0;
    font-size: 0.95rem;
    color: #1e293b;
  }

  .col-head span {
    font-size: 0.8rem;
    background: #fff;
    color: #475569;
    border-radius: 999px;
    padding: 0.15rem 0.5rem;
    border: 1px solid #cbd5e1;
  }
</style>

// vue-nuxt/01-beginner/lab/solution/src/App.vue
<script setup>
import { provide, ref } from 'vue'
import { useTaskBoard } from './composables/useTaskBoard.js'
import TaskColumn from './components/TaskColumn.vue'
import TaskForm from './components/TaskForm.vue'

const theme = ref('light')
provide('theme', theme)

const {
  statuses,
  priorityFilter,
  byStatus,
  stats,
  addTask,
  moveNext,
  toggleDone,
} = useTaskBoard()

function toggleTheme() {
  theme.value = theme.value === 'light' ? 'dark' : 'light'
}
</script>

<template>
  <main :class="['board', theme]">
    <header class="top">
      <div>
        <h1>Reactive Task Board</h1>
        <p class="stats">
          todo {{ stats.todo }} · doing {{ stats.doing }} · done {{ stats.done }}
          (แสดง {{ stats.total }})
        </p>
      </div>
      <div class="controls">
        <label>
          Priority
          <select v-model="priorityFilter">
            <option value="all">all</option>
            <option value="low">low</option>
            <option value="medium">medium</option>
            <option value="high">high</option>
          </select>
        </label>
        <button type="button" @click="toggleTheme">Theme: {{ theme }}</button>
      </div>
    </header>

    <TaskForm @create="addTask" />

    <div class="columns">
      <TaskColumn
        v-for="status in statuses"
        :key="status"
        :title="status"
        :tasks="byStatus[status]"
        @move-next="moveNext"
        @toggle-done="toggleDone"
      />
    </div>
  </main>
</template>

<style>
:root {
  color-scheme: light dark;
}
body {
  margin: 0;
}
.board {
  min-height: 100vh;
  font-family: 'Segoe UI', ui-sans-serif, system-ui, sans-serif;
  padding: 1.5rem;
  background: linear-gradient(160deg, #f7fafc, #e8eef5);
  color: #1a202c;
}
.board.dark {
  background: linear-gradient(160deg, #0f172a, #1e293b);
  color: #e2e8f0;
}
.top {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  flex-wrap: wrap;
  align-items: flex-start;
}
.stats {
  opacity: 0.75;
  margin: 0.25rem 0 0;
}
.controls {
  display: flex;
  gap: 0.75rem;
  align-items: center;
}
.columns {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 1rem;
  margin-top: 1.25rem;
}
button,
select,
input {
  font: inherit;
}
button {
  cursor: pointer;
}
@media (max-width: 800px) {
  .columns {
    grid-template-columns: 1fr;
  }
}
</style>
