// vue-nuxt/03-expert/lab/solution/pages/forbidden.vue
<template>
  <main class="mx-auto max-w-lg px-4 py-12">
    <h1 class="text-2xl font-semibold text-red-700">403 Forbidden</h1>
    <p class="mt-2 text-slate-600">Role ของคุณไม่มีสิทธิ์เข้าหน้านี้</p>
    <NuxtLink to="/dashboard" class="mt-4 inline-block text-sm underline">
      กลับ Dashboard
    </NuxtLink>
  </main>
</template>

// svelte/03-expert/lab/solution/src/routes/forbidden/+page.svelte
<svelte:head>
  <title>Forbidden</title>
</svelte:head>

<main class="mx-auto max-w-3xl space-y-4 px-4 py-10">
  <h1 class="text-2xl font-semibold text-rose-300">403 — Forbidden</h1>
  <p class="text-slate-400">
    คุณไม่มีสิทธิ์ admin สำหรับรายงานนี้ (ลอง login ด้วย <code class="text-teal-300">admin</code>)
  </p>
  <a class="text-teal-300 hover:underline" href="/orders">กลับ Orders</a>
</main>
