// svelte/03-expert/lab/solution/src/routes/login/+page.svelte
<script lang="ts">
  let { form } = $props();
</script>

<svelte:head>
  <title>Login</title>
</svelte:head>

<main class="mx-auto max-w-md space-y-6 px-4 py-10">
  <h1 class="text-2xl font-semibold text-slate-50">Login</h1>
  <p class="text-xs text-amber-300">DEMO-ONLY — educational session tokens</p>

  {#if form?.error}
    <p class="rounded border border-rose-800 bg-rose-950/40 px-3 py-2 text-sm text-rose-300">
      {form.error}
    </p>
  {/if}

  <form method="POST" class="space-y-4 rounded-lg border border-slate-800 bg-slate-900/50 p-5">
    <div class="space-y-1">
      <label class="text-xs text-slate-500" for="username">Username</label>
      <input
        id="username"
        name="username"
        required
        class="w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-sm focus:border-teal-500 focus:outline-none"
        autocomplete="username"
      />
    </div>
    <div class="space-y-1">
      <label class="text-xs text-slate-500" for="password">Password</label>
      <input
        id="password"
        name="password"
        type="password"
        required
        class="w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-sm focus:border-teal-500 focus:outline-none"
        autocomplete="current-password"
      />
    </div>
    <button
      type="submit"
      class="w-full rounded bg-teal-600 px-4 py-2 text-sm font-medium text-white hover:bg-teal-500"
    >
      Sign in
    </button>
  </form>

  <ul class="text-xs text-slate-500">
    <li>admin / admin123</li>
    <li>editor / editor123</li>
    <li>user / user123</li>
  </ul>
</main>

// react-next/03-expert/examples/03-fullstack-patterns/app/(auth)/login/page.tsx
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';

type Props = {
  searchParams: Promise<{ from?: string }>;
};

export default async function LoginPage({ searchParams }: Props) {
  const { from } = await searchParams;

  async function login() {
    'use server';
    const jar = await cookies();
    jar.set('session', 'demo-user', {
      httpOnly: true,
      sameSite: 'lax',
      path: '/',
    });
    redirect(from && from.startsWith('/') ? from : '/dashboard');
  }

  return (
    <main className="mx-auto max-w-md space-y-4 rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
      <h1 className="text-xl font-bold">Login (demo)</h1>
      <p className="text-sm text-slate-600">
        กดปุ่มเพื่อตั้ง cookie <code>session</code> — Middleware จะปล่อยเข้า /dashboard
      </p>
      <form action={login}>
        <button
          type="submit"
          className="w-full rounded-md bg-teal-700 px-4 py-2 font-semibold text-white"
        >
          เข้าสู่ระบบ
        </button>
      </form>
    </main>
  );
}
