// vue-nuxt/03-expert/lab/solution/pages/dashboard/index.vue
<script setup>
definePageMeta({
  middleware: ['auth'],
})

const auth = useAuthStore()
const { data, pending } = await useFetch('/api/orders', { key: 'ops-orders' })
const rows = computed(() => data.value?.items ?? [])
</script>

<template>
  <main class="mx-auto max-w-6xl px-4 py-8">
    <div class="mb-6 flex flex-wrap items-center justify-between gap-3">
      <div>
        <h1 class="text-2xl font-semibold tracking-tight">Orders</h1>
        <p class="text-sm text-slate-600">
          {{ auth.user?.name }} · {{ auth.user?.role }}
        </p>
      </div>
      <div class="flex gap-2">
        <NuxtLink
          to="/dashboard/admin"
          class="rounded-md border border-slate-300 bg-white px-3 py-2 text-sm"
        >
          Admin Report
        </NuxtLink>
        <button
          type="button"
          class="rounded-md border border-slate-300 bg-white px-3 py-2 text-sm"
          @click="auth.logout(); navigateTo('/login')"
        >
          Logout
        </button>
      </div>
    </div>

    <p v-if="pending" class="text-slate-500">Loading orders…</p>
    <OrdersGrid v-else :rows="rows" />
  </main>
</template>

// react-next/03-expert/examples/03-fullstack-patterns/app/dashboard/page.tsx
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import { DashboardGrid } from '@/components/DashboardGrid';
import { TodoPanel } from '@/components/TodoPanel';
import { todoRepo } from '@/lib/todoRepo';

export default async function DashboardPage() {
  const jar = await cookies();
  if (!jar.get('session')) {
    redirect('/login');
  }

  const todos = todoRepo.list();

  async function logout() {
    'use server';
    const c = await cookies();
    c.delete('session');
    redirect('/login');
  }

  return (
    <main className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold">Ops Dashboard</h1>
          <p className="text-sm text-slate-600">Responsive grid + Server Actions</p>
        </div>
        <form action={logout}>
          <button
            type="submit"
            className="rounded-md bg-slate-700 px-3 py-1.5 text-sm font-semibold text-white"
          >
            Logout
          </button>
        </form>
      </div>

      <DashboardGrid
        stats={[
          { label: 'Open todos', value: String(todos.filter((t) => !t.done).length) },
          { label: 'Done', value: String(todos.filter((t) => t.done).length) },
          { label: 'API', value: '/api/todos' },
          { label: 'Auth', value: 'cookie session' },
        ]}
      />

      <TodoPanel todos={todos} />
    </main>
  );
}
