// react-next/03-expert/lab/solution/app/(auth)/login/page.tsx
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';

type Props = { searchParams: Promise<{ from?: string }> };

export default async function LoginPage({ searchParams }: Props) {
  const { from } = await searchParams;

  async function login() {
    'use server';
    const jar = await cookies();
    jar.set('session', 'ops-admin', {
      httpOnly: true,
      sameSite: 'lax',
      path: '/',
    });
    redirect(from && from.startsWith('/') ? from : '/dashboard');
  }

  return (
    <main className="mx-auto max-w-md px-4 py-16">
      <div className="space-y-4 rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
        <h1 className="text-xl font-bold">Ops Login</h1>
        <p className="text-sm text-slate-600">
          Demo auth — ตั้ง cookie แล้วให้ Middleware ปล่อยเข้า dashboard
        </p>
        <form action={login}>
          <button
            type="submit"
            className="w-full rounded-md bg-teal-700 px-4 py-2 font-semibold text-white"
          >
            เข้าสู่ระบบ
          </button>
        </form>
      </div>
    </main>
  );
}

// vue-nuxt/03-expert/lab/solution/pages/login.vue
<script setup>
const auth = useAuthStore()

function go(role) {
  auth.loginAs(role)
  return navigateTo('/dashboard')
}
</script>

<template>
  <main class="mx-auto max-w-lg px-4 py-12">
    <h1 class="text-2xl font-semibold">Login</h1>
    <p class="mt-2 text-slate-600">เลือก role สำหรับ lab (จำลอง session ใน Pinia)</p>
    <div class="mt-6 flex flex-wrap gap-3">
      <button
        type="button"
        class="rounded-md bg-slate-900 px-4 py-2 text-sm text-white"
        @click="go('admin')"
      >
        Login as admin
      </button>
      <button
        type="button"
        class="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm"
        @click="go('viewer')"
      >
        Login as viewer
      </button>
    </div>
  </main>
</template>
